// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkhfDqFaF3ZpaujN_LowY7lKrZoaEvTNo',
    appId: '1:769266658540:web:cc6ad69a0a47d8db2289c9',
    messagingSenderId: '769266658540',
    projectId: 'financi-e1b11',
    authDomain: 'financi-e1b11.firebaseapp.com',
    storageBucket: 'financi-e1b11.firebasestorage.app',
    measurementId: 'G-WMXEEL7E31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUTxWzNn4hnU1ltKFpqlq9B87uDUMrRAc',
    appId: '1:769266658540:android:d7d18233698bd88d2289c9',
    messagingSenderId: '769266658540',
    projectId: 'financi-e1b11',
    storageBucket: 'financi-e1b11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAksxQ9OpvnZy2mxUkt7kjcHesjhHz__u0',
    appId: '1:769266658540:ios:9a97dcd795bdc7fb2289c9',
    messagingSenderId: '769266658540',
    projectId: 'financi-e1b11',
    storageBucket: 'financi-e1b11.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAksxQ9OpvnZy2mxUkt7kjcHesjhHz__u0',
    appId: '1:769266658540:ios:9a97dcd795bdc7fb2289c9',
    messagingSenderId: '769266658540',
    projectId: 'financi-e1b11',
    storageBucket: 'financi-e1b11.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkhfDqFaF3ZpaujN_LowY7lKrZoaEvTNo',
    appId: '1:769266658540:web:aa4d9a0f7f6c10102289c9',
    messagingSenderId: '769266658540',
    projectId: 'financi-e1b11',
    authDomain: 'financi-e1b11.firebaseapp.com',
    storageBucket: 'financi-e1b11.firebasestorage.app',
    measurementId: 'G-G5X9PMHRES',
  );
}
